package(default_visibility = ["//visibility:public"])

cc_library(
  name = "discord_bot",
  srcs = ["discord_bot.cc"],
  hdrs = ["discord_bot.hh"],
  deps = [
    "//core:bot_io",
    "@dpp//:dpp",
  ],
)
